export const mockFoodItems = [
  {
    id: "1",
    name: "Paneer Rice Bowl",
    businessName: "FreshBite Kitchen",
    location: "Noida Sector 62",
    distance: 2.1, // km away
    distanceText: "2.1 km away",
    image:
      "https://images.unsplash.com/photo-1546069901-ba9599a7e63c?auto=format&fit=crop&w=800&q=80",
    quantity: 12,
    quantityText: "12 meals available",
    price: 79,
    originalPrice: 180,
    discountPercent: 56,
    pickupDeadline: "8:30 PM",
    category: "Prepared Meals",
    status: "Available", // Available, Expiring Soon, Almost Expired
    description:
      "Delicious cottage cheese cubes cooked in rich tomato gravy served over fragrant steamed basmati rice with side mint chutney.",
    dietary: ["Vegetarian", "Gluten-Free"],
    fssaiVerified: true,
    rating: 4.8,
    reviewsCount: 142,
    prepTime: "Today at 1:30 PM",
    packaging: "Eco-friendly sugarcane pulp bowl with tamper-evident seal",
  },
  {
    id: "2",
    name: "Assorted Artisanal Bakery Box",
    businessName: "The French Loaf",
    location: "Noida Sector 18",
    distance: 4.5,
    distanceText: "4.5 km away",
    image:
      "https://images.unsplash.com/photo-1509440159596-0249088772ff?auto=format&fit=crop&w=800&q=80",
    quantity: 8,
    quantityText: "8 boxes available",
    price: 120,
    originalPrice: 350,
    discountPercent: 66,
    pickupDeadline: "7:45 PM",
    category: "Bakery & Pastries",
    status: "Expiring Soon",
    description:
      "Freshly baked sourdough slices, butter croissants, multigrain rolls, and dark chocolate muffins packaged straight from evening display.",
    dietary: ["Vegetarian", "Contains Dairy", "Contains Gluten"],
    fssaiVerified: true,
    rating: 4.9,
    reviewsCount: 210,
    prepTime: "Baked today at 8:00 AM",
    packaging: "Recyclable cardboard bakery box",
  },
  {
    id: "3",
    name: "North Indian Buffet Meal Set",
    businessName: "Radisson Blu Hotel",
    location: "Noida Sector 55",
    distance: 3.2,
    distanceText: "3.2 km away",
    image:
      "https://images.unsplash.com/photo-1585937421612-70a008356fbe?auto=format&fit=crop&w=800&q=80",
    quantity: 45,
    quantityText: "45 meals available",
    price: 150,
    originalPrice: 650,
    discountPercent: 77,
    pickupDeadline: "9:00 PM",
    category: "Catering Surplus",
    status: "Available",
    description:
      "Premium lunch buffet surplus containing Dal Makhani, Paneer Butter Masala, Jeera Rice, Tandoori Roti, and Gulab Jamun.",
    dietary: ["Vegetarian", "North Indian"],
    fssaiVerified: true,
    rating: 4.9,
    reviewsCount: 380,
    prepTime: "Cooked today at 2:00 PM",
    packaging: "Heavy-duty insulated aluminum containers",
  },
  {
    id: "4",
    name: "South Indian Tiffin Combo",
    businessName: "Sagar Ratna",
    location: "Noida Sector 32",
    distance: 1.8,
    distanceText: "1.8 km away",
    image:
      "https://images.unsplash.com/photo-1610192244261-3f33de3f55e4?auto=format&fit=crop&w=800&q=80",
    quantity: 15,
    quantityText: "15 meals available",
    price: 60,
    originalPrice: 160,
    discountPercent: 62,
    pickupDeadline: "7:15 PM",
    category: "Prepared Meals",
    status: "Almost Expired",
    description:
      "Hot steamed Idlis, Medu Vada, and Mini Masala Dosa served with fresh coconut chutney and piping hot Sambhar.",
    dietary: ["Vegetarian", "Vegan Option"],
    fssaiVerified: true,
    rating: 4.7,
    reviewsCount: 195,
    prepTime: "Cooked today at 4:00 PM",
    packaging: "Compartmentalized leak-proof meal tray",
  },
  {
    id: "5",
    name: "Farm Fresh Organic Vegetable Basket",
    businessName: "GreenGrocer Organics",
    location: "Greater Noida West",
    distance: 7.2,
    distanceText: "7.2 km away",
    image:
      "https://images.unsplash.com/photo-1610348725531-843dff563e2c?auto=format&fit=crop&w=800&q=80",
    quantity: 20,
    quantityText: "20 baskets available",
    price: 99,
    originalPrice: 280,
    discountPercent: 65,
    pickupDeadline: "9:30 PM",
    category: "Groceries & Produce",
    status: "Available",
    description:
      "Assorted farm-fresh organic produce including spinach, bell peppers, tomatoes, cucumbers, and zucchini with minor cosmetic blemishes.",
    dietary: ["Raw Produce", "Vegan", "Organic"],
    fssaiVerified: true,
    rating: 4.6,
    reviewsCount: 88,
    prepTime: "Harvested yesterday",
    packaging: "Jute grocery bag",
  },
  {
    id: "6",
    name: "Cloud Kitchen Bento Bowls",
    businessName: "SpiceBox Kitchens",
    location: "Noida Sector 63",
    distance: 2.8,
    distanceText: "2.8 km away",
    image:
      "https://images.unsplash.com/photo-1512621776951-a57141f2eefd?auto=format&fit=crop&w=800&q=80",
    quantity: 25,
    quantityText: "25 bowls available",
    price: 89,
    originalPrice: 220,
    discountPercent: 60,
    pickupDeadline: "8:45 PM",
    category: "Prepared Meals",
    status: "Available",
    description:
      "Nutritious quinoa grain bowls topped with roasted Mediterranean vegetables, chickpeas, and lemon tahini dressing.",
    dietary: ["Healthy", "Vegan", "Gluten-Free"],
    fssaiVerified: true,
    rating: 4.8,
    reviewsCount: 160,
    prepTime: "Prepared today at 3:00 PM",
    packaging: "Biodegradable kraft paper container",
  },
];
